apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: default
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090      # Internal cluster port
      targetPort: 9090 # Container port
      nodePort: 32000  # Port to access externally

